### ISSUE TITLE
What is Web Service, Microservice, API and Endpoint

### ISSUE THREAD

**Issue by adave10100** [in28minutes/learning-paths-cloud-and-devops#4]

**Comment by in28minutes** [comment]
Added to fundamentals - https://docs.google.com/spreadsheets/d/1EqDmRLIaqR2uzWdDshBs5WSo5ZazlXclvEupNqNsSZU/edit#gid=41683914

**Comment by adave10100** [comment]
I was hoping to have one session where we share overall differences among these four. Then we may have individual sessions on each one of these.

**Comment by in28minutes** [comment]
Sounds good. Added it here -
https://docs.google.com/spreadsheets/d/1EqDmRLIaqR2uzWdDshBs5WSo5ZazlXclvEupNqNsSZU/edit#gid=41683914
(Sheet - Fundamentals - K2)

Ranga
